(define (problem problem0)
  (:domain escape)
  (:objects )
  (:init           (at_0-player0-cell_0_1 )
          (at_1-block0-cell_0_0 )
          (at_1-block1-cell_1_2 )
          (is_door-cell_1_0 )
          (is_hole-cell_2_2 )
          (leftOf-cell_0_0-cell_1_0 )
          (leftOf-cell_0_1-cell_1_1 )
          (leftOf-cell_0_2-cell_1_2 )
          (leftOf-cell_1_0-cell_2_0 )
          (leftOf-cell_1_1-cell_2_1 )
          (leftOf-cell_1_2-cell_2_2 )
          (rightOf-cell_1_0-cell_0_0 )
          (rightOf-cell_1_1-cell_0_1 )
          (rightOf-cell_1_2-cell_0_2 )
          (rightOf-cell_2_0-cell_1_0 )
          (rightOf-cell_2_1-cell_1_1 )
          (rightOf-cell_2_2-cell_1_2 )
          (above-cell_0_0-cell_0_1 )
          (above-cell_0_1-cell_0_2 )
          (above-cell_1_0-cell_1_1 )
          (above-cell_1_1-cell_1_2 )
          (above-cell_2_0-cell_2_1 )
          (above-cell_2_1-cell_2_2 )
          (below-cell_0_1-cell_0_0 )
          (below-cell_0_2-cell_0_1 )
          (below-cell_1_1-cell_1_0 )
          (below-cell_1_2-cell_1_1 )
          (below-cell_2_1-cell_2_0 )
          (below-cell_2_2-cell_2_1 )
          (clear-cell_0_2 )
          (clear-cell_1_1 )
          (clear-cell_2_1 )
          (clear-cell_2_0 )
          (clear-cell_1_0 )
)  (:goal (and
   
          (at_0-player0-cell_1_0 )
          (at_1-block0-cell_0_0 )
          (is_door-cell_1_0 )
          (is_hole-cell_2_2 )
          (leftOf-cell_0_0-cell_1_0 )
          (leftOf-cell_0_1-cell_1_1 )
          (leftOf-cell_0_2-cell_1_2 )
          (leftOf-cell_1_0-cell_2_0 )
          (leftOf-cell_1_1-cell_2_1 )
          (leftOf-cell_1_2-cell_2_2 )
          (rightOf-cell_1_0-cell_0_0 )
          (rightOf-cell_1_1-cell_0_1 )
          (rightOf-cell_1_2-cell_0_2 )
          (rightOf-cell_2_0-cell_1_0 )
          (rightOf-cell_2_1-cell_1_1 )
          (rightOf-cell_2_2-cell_1_2 )
          (above-cell_0_0-cell_0_1 )
          (above-cell_0_1-cell_0_2 )
          (above-cell_1_0-cell_1_1 )
          (above-cell_1_1-cell_1_2 )
          (above-cell_2_0-cell_2_1 )
          (above-cell_2_1-cell_2_2 )
          (below-cell_0_1-cell_0_0 )
          (below-cell_0_2-cell_0_1 )
          (below-cell_1_1-cell_1_0 )
          (below-cell_1_2-cell_1_1 )
          (below-cell_2_1-cell_2_0 )
          (below-cell_2_2-cell_2_1 )
          (clear-cell_2_1 )
          (clear-cell_2_0 )
          (clear-cell_1_0 )
          (clear-cell_0_1 )
          (clear-cell_0_2 )
          (clear-cell_1_2 )
          (clear-cell_1_1 )
          (escaped- )
)
)
)
